version: "3.7"
services:
  blog:
    build:
      context: ./blog
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: blog
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8080:8000
    volumes:
      - ./blog:/app/blog
    depends_on:
      - db
    networks:
      - app

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: "blog"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - app

networks:
  app:
    driver: bridge